export const PATCH_NOTES = [
  { version: "1.4.0", th: ["หน้า “วิเคราะห์” ใหม่: ดูรายสัปดาห์ รายเดือน รายปี พร้อมทรัพย์สินสุทธิ อัตราการออม แนวโน้มเงินคงเหลือ และรายจ่ายแยกหมวด", "เพิ่มหน้า “ข้อมูลส่วนตัว” และกรอบโปรไฟล์บนแถบบน (มือถือแสดงกรอบ, พีซีแสดงชื่อเต็ม พร้อมแถบบนสำหรับจอใหญ่)", "ย้ายปุ่มเมนูกลับมาไว้ฝั่งซ้าย และปัดจากขอบซ้ายเพื่อเปิดเมนู", "เพิ่มปุ่มลัดเข้าหน้าวิเคราะห์จากหน้าภาพรวม", "แก้ช่องวันที่และช่องยอดตั้งต้นในฟอร์มเพิ่มบัญชี", "แสดงกำไร/ขาดทุนการลงทุนด้วยทศนิยม 2 ตำแหน่ง"], en: ["New Analytics page: weekly / monthly / yearly views with net worth, savings rate, net-cashflow trend and spending by category", "Add a Profile page and a header identity chip (avatar-only on mobile, full name on desktop, with a desktop top bar)", "Move the menu button back to the left; swipe from the left edge to open it", "Add a shortcut to Analytics from the overview", "Fix the date and opening-balance fields in the add-account form", "Show investment gain/loss with two decimals"] },
  { version: "1.3.0", th: ["ปรับดีไซน์แถบเมนู หน้าต่าง และแจ้งเตือนเป็นสไตล์กระจกโปร่ง (liquid glass) รองรับทั้งธีมสว่างและมืด", "ย่อการ์ดภาพรวมทรัพย์สินสุทธิให้กระชับ อ่านง่ายขึ้น", "จัดหน้าพอร์ตใหม่: ลดตัวเลขซ้ำ และรวมปุ่มเพิ่มสินทรัพย์ให้อยู่ที่เดียว"], en: ["Refresh the nav bars, sheets and toasts with a liquid-glass look in both light and dark themes", "Tighten the net-worth overview card", "Reorganise the portfolio page: fewer duplicate figures, one place to add assets"] },
  { version: "1.2.0", th: ["บันทึกสีหลักไว้กับบัญชีผู้ใช้และซิงก์ข้ามอุปกรณ์", "เพิ่มเมนู Patch Notes พร้อมจุดแจ้งเตือนเวอร์ชันใหม่", "ปรับอีเมลผู้ดูแลระบบ"], en: ["Sync the app accent color with the user account", "Add Patch Notes with an unread update indicator", "Update the administrator email"] },
  { version: "1.1.6", th: ["แสดงความคืบหน้า OCR และผลลัพธ์ทีละภาพ"], en: ["Show OCR progress and results one image at a time"] },
  { version: "1.1.5", th: ["ย้ายแจ้งเตือนให้อยู่ใต้ Dynamic Island"], en: ["Keep update notifications below the Dynamic Island"] },
  { version: "1.1.4", th: ["แสดงจำนวนเงินด้วยทศนิยม 2 ตำแหน่ง"], en: ["Display monetary amounts with two decimal places"] },
  { version: "1.1.3", th: ["แก้ OCR นำเข้าหุ้นหลายรายการและรักษาทศนิยม"], en: ["Improve bulk holdings OCR and decimal accuracy"] },
  { version: "1.1.2", th: ["เก็บและคำนวณจำนวนเงินโดยไม่ตัดทศนิยม"], en: ["Preserve monetary decimals in calculations"] },
  { version: "1.1.1", th: ["เพิ่มการนำเข้าสินทรัพย์หลายรายการด้วย OCR"], en: ["Restore bulk asset import with OCR"] },
  { version: "1.1.0", th: ["เพิ่มราคาหุ้นและอัตราแลกเปลี่ยนล่าสุด", "ปรับหน้าพอร์ตและบัญชี พร้อมลากวางเพื่อโอนเงิน", "เพิ่มการอ่านสลิปลงทุน"], en: ["Add current stock prices and exchange rates", "Redesign portfolios and accounts with drag-to-transfer", "Add investment slip scanning"] },
  { version: "1.0.0", th: ["Wally เวอร์ชันแรกสำหรับจัดการบัญชี รายรับ รายจ่าย และการโอนเงิน"], en: ["Initial Wally release for accounts, income, expenses, and transfers"] },
] as const;
